### ISSUE TITLE
Any information on the status of this project?

### ISSUE THREAD

**Issue by UweBonnes** [zeph/wicd#3]
Hello,

what is the status of this project. In what state is it?
- It does not work?
- It should work?
- It works for me(you)?
- It works?

**Comment by zeph** [comment]
sorry mate, you find the official repo on launchpad.net 

yes, I've been slacking for several reasons... there are 180-something bugs on the site... wanna help?

it does work on my laptop, it could work better... needs packaging, Alex is doing it, but needs my input (i'm upstream)

**Comment by UweBonnes** [comment]
Well, stock Wicd is Python 2 and already is or will be removed soon from most distributions. If your effort at least works for you, I may give it a try .

**Comment by zeph** [comment]
look at https://code.launchpad.net/wicd (it is upstream ...works on my laptop :D )

**Comment by zeph** [comment]
@UweBonnes working with Alex from Debian to get back into the distro 

https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=wicd

**Comment by xtaran** [comment]
> @UweBonnes working with Alex from Debian

Took me a moment to understand that part. I guess it's missing a colon after "@UweBonnes" as I've never heard of him before this issue and I can't remember working with him on wicd in Debian. (And my name is "Axel", not "Alex".)

>  to get back into the distro

With the exception of Debian Testing it's not removed anywhere in Debian. And the Python 3 version is already in Debian Experimental. Still not as stable as before, though, and the wicd-gtk part is non-functional with Python 3 at the moment, but we're on the right way...

**Comment by zeph** [comment]
it's been a long day... thanks for the patience & clarification @xtaran  :)
